blog/urls.py
from django.urls import path
from .views import render_publicaciones, publicaciones_detalles

app_name = "blog"
urlpatterns = [
    path("", render_publicaciones, name="publicaciones"),
    path(
        "<int:publicacion_id>",
        publicaciones_detalles,
        name="detalle_publicaciones",
    ),
]

django_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from portafolio import views


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.home, name="home"),
    path("blog/", include("blog.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
import datetime


class Publicacion(models.Model):
    titulo = models.CharField(max_length=100)
    descripcion = models.TextField()
    imagen = models.ImageField(upload_to="blog/imagenes")
    fecha = models.DateField(default=datetime.date.today)

    def __str__(self) -> str:
        return self.titulo

portafolio/models.py
from django.db import models
from django.db.models.fields import CharField, URLField, DateField
from django.db.models.fields.files import ImageField
from datetime import date


class Proyecto(models.Model):
    titulo = CharField(max_length=100)
    descripcion = CharField(max_length=250)
    imagen = ImageField(upload_to="portfolio/imagenes/")
    url = URLField(blank=True)
    fecha = DateField(default=date.today)

    def __str__(self) -> str:
        return self.titulo

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Publicacion


def render_publicaciones(request):
    total_publicaciones = Publicacion.objects.count()
    publicaciones = Publicacion.objects.order_by("-fecha")
    return render(
        request,
        "blog.html",
        {"publicaciones": publicaciones, "total_publicaciones": total_publicaciones},
    )


def publicaciones_detalles(request, publicacion_id):
    publicacion = get_object_or_404(Publicacion, pk=publicacion_id)
    return render(request, "detalle_publicacion.html", {"publicacion": publicacion})

portafolio/views.py
from django.shortcuts import render
from .models import Proyecto


def home(request):
    proyectos = Proyecto.objects.all()

    return render(request, "home.html", {"proyectos": proyectos})

blog/templates/blog.html
{% extends "layout.html"%} {% block content%}
<h1>Publicaciones</h1>
<h3>Existen {{total_publicaciones}} Publicaciones {{total_publicaciones|pluralize}}</h3>
{% for publicacion in Publicaciones %}
<div class="py-3">
    <div class="card card-body bg-black">
        <div class="row">
            <div class="col-3">
                <img class="img-fluid" src="{{publicacion.imagen.url}}" alt="{{publicacion.titulo}}">

            </div>
            <div class="col-9">
                <h1>{{publicacion.titulo}}</h1>
                <p>{{publicacion.fecha|date:'M d Y'}}</p>
                <p>{{publicacion.descripcion|striptags|truncatechars:100 }}</p>
                <a href="{% url 'blog:detalle_publicaciones' publicacion_id%}"
                    class="btn btn-primary">{{publicacion.titulo}}</a>

            </div>
        </div>
    </div>

</div>
{% endfor%}

{% endblock%}

blog/templates/detalle_publicacion.html
{% extends "layout.html" %}
{% block content %}
<div class="text-center">
    <h1>{{publicacion.titulo}}</h1>
    <h2 class="my-2 h5 text-muted">{{publicacion.fecha|date:'F jS Y'}}</h2>

    <img src="{{publicacion.imagen.url}}" alt="{{publicacion.titulo}}" class="img-fluid">
    <div class="my-4">
        {{publicacion.descripcion|safe}}
    </div>
</div>
{% endblock %}

portafolio/templates/home.html
{% extends "layout.html"%}
{% block content%}

{% load static %}
<header class="row bg-black">
    <div class="col-md-4">
        <img src="{% static 'portfolio/yo-nuevo.jpg' %}">
    </div>
    <div class="col-md-8 my-auto p-4">
        <h1>Soy <strong>Horacio Laphitz<strong></h1>
        <h3>Python Developer - Data Analyst</h3>
        <p>Soy un profesional comprometido con la solución de problemas
            empresariales, destacando por mi meticulosidad en los detalles y la mejora
            de procesos.
            Manejo herramientas avanzadas para ETL y tengo dominio de Python, R, SQL,
            PowerBI, Tableau, así como de modelos de Machine Learning y Deep
            Learning, Data-as-a-Service, Data Warehouse y Data Lakes.</p>
        <a href="{% static 'portfolio/cv.pdf'%}" class="btn btn-primary btn-lg rounded-0 my-3">Descargar Curriculum
            vitae</a>
    </div>

</header>

<div class="row my-4 text-center">
    <h3>Mis Proyectos</h3>
    <p>Estos son todos los Proyectos en los cuales trabaje hasta el <br>Momento </p>
    {% for proyecto in proyectos %}
    <div class="col md-4 p-4">
        <div class="card bg-black card-proyecto">
            <img src="{{ proyecto.imagen.url }}" alt="{{ proyecto.titulo }}" class="card-img-top" />
            <div class="card card-body">
                <h2>{{ proyecto.titulo }}</h2>
                <p>{{ proyecto.descripcion }}</p>
                {% if proyecto.url %}
                <a href="{{proyecto.url}}" class="btn btn-light rounded-0 btn-sm" target="_blank">{{proyecto.url}}</a>

                {% endif %}
            </div>
        </div>
    </div>
    {% endfor %}
    {% endblock %}
</div>

portafolio/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
    
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
<link rel="stylesheet" href='{% static "main.css" %}'>
</head>

<body class="text-light">
    {% include 'partials/navbar.html'%}
    
    <div class="container p-4">
    {% block content %}
    
    {% endblock %}
    </div>
</body>

</html>

portafolio/templates/partials/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-black">
    <div class="container">
      <a class="navbar-brand fw-bold fst-italic" href="/">H.N.L</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ms-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'blog:publicaciones'%}">Blog</a>
          </li>
          <li class="nav-item d-flex align-items-center">
            <a class="btn btn-primary btn-sm" href="{% static 'portfolio/cv.pdf' %}" target="_blank">Descargar CV</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>